name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Run from node docker image
      uses: docker://node:alpine
    - name: Run lint scripts
      run: sh _scripts/lint_all.sh
